### ISSUE TITLE
(on)submit events never triggered after submit action

### ISSUE THREAD

**Issue by veacks** [paypal/nemo#59]
Hi,

I'm working a single page app application which provides a non-js alternative based on Kraken/Dustjs/Backbone.

My problem is, when I try to submit my forms, it always submit without triggering the onsubmit event attached to it.

I have tried many solutions surch as 
> @userView.sendInvitationForm().click() #Submit button

> @userView.inviteUserForm().submit() #Form

> nemo.driver.executeScript "$(\"#user-invite form [type=submit]\").trigger(\"click\")"

> nemo.driver.executeScript "$(\"#user-invite form\")[0].submit()"

> nemo.driver.executeScript "$(\"#user-invite form\").submit()"

Each one of them submit the form without trigger the onsubmit event.

I know it's more likely an issue with webdriver itself, but I wonder if some one have found a workaround to make it work.

Thanks,
Val.

**Comment by nikulkarni** [comment]
Hey @veacks, you are right, this problem seems to be specific with webdriver. However I'll try to help as much as I can. Can you answer following questions?
1. What is your nemo version?
2. what browser and version are you using?
3. Does this problem occur on all browsers?
4. Is your site publicly available or is this problem reproducible elsewhere that I can try out?

**Comment by grawk** [comment]
close due to inactivity
